# Generated by Django 5.2.17 on 2026-09-17 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="地図ピン表示に使う絵文字やアイコン識別子（例: 🍜）",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2F6F4E",
                        help_text="地図ピンの色（例: #2F6F4E）",
                        max_length=7,
                    ),
                ),
                (
                    "student_registrable",
                    models.BooleanField(
                        default=False,
                        help_text="経営者が存在しないカテゴリ（ATM・バス停・トイレ等）。学生ロールでも登録できる。",
                    ),
                ),
            ],
            options={
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="spot_images/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reject_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spots",
                        to="spots.category",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "スポット",
                "verbose_name_plural": "スポット",
                "ordering": ["-created_at"],
            },
        ),
    ]
