# Generated by Django 5.2.17 on 2026-09-17 03:27

from django.db import migrations

CATEGORIES = [
    {"name": "安い飯屋", "icon_class": "🍜", "color": "#D97706", "student_registrable": False},
    {"name": "勉強できる場所", "icon_class": "📚", "color": "#2563EB", "student_registrable": False},
    {"name": "印刷できる場所", "icon_class": "🖨️", "color": "#7C3AED", "student_registrable": False},
    {"name": "ATM", "icon_class": "💴", "color": "#2F6F4E", "student_registrable": True},
    {"name": "トイレ", "icon_class": "🚻", "color": "#0891B2", "student_registrable": True},
    {"name": "コンセントがある店", "icon_class": "🔌", "color": "#DB2777", "student_registrable": False},
    {"name": "駐輪場", "icon_class": "🚲", "color": "#57606A", "student_registrable": True},
    {"name": "バス停", "icon_class": "🚌", "color": "#0EA5E9", "student_registrable": True},
    {"name": "コインランドリー", "icon_class": "🧺", "color": "#9333EA", "student_registrable": True},
    {"name": "古本屋", "icon_class": "📖", "color": "#92400E", "student_registrable": False},
    {"name": "深夜営業店", "icon_class": "🌙", "color": "#1E3A5F", "student_registrable": False},
    {"name": "無料Wi-Fi", "icon_class": "📶", "color": "#16A34A", "student_registrable": True},
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("spots", "Category")
    for data in CATEGORIES:
        Category.objects.update_or_create(name=data["name"], defaults=data)


def remove_categories(apps, schema_editor):
    Category = apps.get_model("spots", "Category")
    Category.objects.filter(name__in=[c["name"] for c in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
