# Generated by Django 5.2.17 on 2026-09-25 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=100, verbose_name="事業者名"),
                ),
                (
                    "representative_name",
                    models.CharField(max_length=100, verbose_name="代表者名"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="法人番号は13桁の数字で入力してください。",
                                regex="^\\d{13}$",
                            )
                        ],
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="連絡先メールアドレス"
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        upload_to="business_verifications/", verbose_name="本人確認書類"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "審査中"),
                            ("approved", "認証済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, verbose_name="却下理由"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "承認申請",
                "verbose_name_plural": "承認申請",
                "ordering": ["-created_at"],
            },
        ),
    ]
